CREATE TABLE [dbo].[dostawcy]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [ds_id] BIGINT NOT NULL, 
    [ds_kod] VARCHAR(10) NULL, 
    [ds_nazwa] VARCHAR(200) NULL, 
    [ds_przedstawiciel] VARCHAR(100) NULL, 
    [ds_stanowisko] VARCHAR(100) NULL, 
    [ds_ulica] VARCHAR(200) NULL, 
    [ds_nrdomu] VARCHAR(15) NULL, 
    [ds_nrlokalu] VARCHAR(15) NULL, 
    [ds_kodpocztowy] VARCHAR(15) NULL, 
    [ds_miasto] VARCHAR(100) NULL, 
    [ds_tel] VARCHAR(50) NULL, 
    [ds_telkom] VARCHAR(50) NULL, 
    [ds_fax] VARCHAR(50) NULL, 
    [ds_email] VARCHAR(100) NULL, 
    [ds_www] VARCHAR(100) NULL, 
    [ds_nip] VARCHAR(100) NULL, 
    [ds_kraj] VARCHAR(100) NULL, 
    [ds_dostawca] BIT NULL, 
    [ds_kooperant] BIT NULL, 
    [ds_projektant] BIT NULL, 
    [ds_info] TEXT NULL
)
