CREATE TABLE dbo.Sample_Table
(
    [fi_id] BIGINT NOT NULL IDENTITY,
    [nazwa] TEXT NOT NULL, 
    [przedstawiciel] TEXT NULL, 
    [stanowisko] TEXT NULL, 
    [ulica] TEXT NOT NULL, 
    [nrdomu] TEXT NULL, 
    [nrlokalu] TEXT NULL, 
    [kodpoczt] TEXT NULL, 
    [miasto] TEXT NOT NULL, 
    [tel] TEXT NULL, 
    [telkom] TEXT NULL, 
    [fax] TEXT NULL, 
    [email] TEXT NULL, 
    [www] TEXT NULL, 
    [nip] TEXT NULL, 
    [info] TEXT NULL, 
    [kraj] TEXT NOT NULL, 
    [dostawca] BIT NULL, 
    [kooperant] BIT NULL, 
    [odbiorca] BIT NULL, 
    [ins_data] DATE NULL, 
    [ins_user] VARCHAR(100) NULL, 
    [upd_data] DATE NULL, 
    [upd_user] VARCHAR(100) NULL, 
    [del_id] BIGINT NULL, 
    [katalog] VARCHAR(100) NULL, 
    [koopdoc] BIT NULL, 
    CONSTRAINT [PK_Sample_Table] PRIMARY KEY ([fi_id])
);